baseurl = "/"
title = "Nik's Data Lake"
author = "Nik Agarwal"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Nik's Data Lake"

[Taxonomies]
  tag = "tags"

[[menu.main]]
    name = "Home"
    url = "https://nik.netlify.com"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/nikdata"
    weight = 2
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/nikagarwal"
    weight = 3
[[menu.main]]
    name = "About"
    url = "/about/"
