baseurl = "https://nik.netlify.app/"
title = "{nik}"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 25

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

[params]
  author = "Nik Agarwal"
  info = "Data Scientist"
  description = "Personal Blog of Nik Agarwal"
  keywords = "blog,data-scientist,personal"
  avatarurl = "img/nikpik.png"
  #gravatar = "john.doe@example.com"

  favicon_32 = "img/favicon.ico"
  favicon_16 = "img/favicon.ico"

  footercontent = ""
  hideFooter = false
  hideCredits = true
  hideCopyright = false
  since = 2018

  enableTwemoji = true

  math = true
  katex = true

  colorScheme = "dark"
  hidecolorschemetoggle = true

  customCSS = ["my_css.css"]
  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  # category = "categories"
  # series = "series"
  # tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/nikdata/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://linkedin.com/in/nik-agarwal"

[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/nikagarwal/"

[[params.social]]
  name = "Reddit"
  icon = "fa fa-reddit-alien fa-2x"
  weight = 4
  url = "https://reddit.com/user/cmdrmac"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "post/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"